### ISSUE TITLE
Incorrect Cursor Positioning After Paste

### ISSUE THREAD

**Issue by seasonedgeek** [coteditor/CotEditor#1326] opened 2022-06-26 23:01 UTC
### Description

Cursor changes column position after pasting (286 characters) text on current line.

### To Reproduce

Step 1. Open a "New Plain Text Window".
Step 2. Paste (286 characters) text as prompted by "blinking" cursor.
Step 3. Press the "return" key.
Step 4. Repeat, steps 2 and 3, eleven (11) times.
Step 5. Repeat step 2 again.

See Error: The "blinking" cursor is positioned at Column 26 after pasting the text (286 characters).

### Expected behavior

The "blinking" cursor should be positioned at Column 287 after pasting the text.

### CotEditor version

4.0.9 (473)

### macOS version

10.15.7 (Build 19H1615)

### Additional context

The above occurs whether or not the plain text file is saved to disk.

**Comment by 1024jp** [comment] 2022-06-27 04:25
The reported phenomenon was not reproduced on the latest CotEditor (v4.3.0 + macOS 12.4).
Could you upload the screencast as well as the sample text?

Because CotEditor for macOS 10.15 is currently not maitained anymore, we'll lte the issue be if it can not be reproduced in the latest CotEditor.

**Comment by 1024jp** [comment] 2022-07-06 11:25
I close this ticket because the version reported is no more supported currently (sorry).
If somebody found the same issue under the latest environment, feel free to report me.

**Closed by 1024jp** 2022-07-06 11:25 UTC
Labels: potential bug
