### ISSUE TITLE
Colourised markdown syntax flashes/visibly refreshes while typing

### ISSUE THREAD

**Issue by prc1212** [coteditor/CotEditor#1241] opened 2022-01-24 23:01 UTC
### Description

I am using CotEditor to write in markdown. It works beautifully except that, when I am typing at full speed, the highlighted syntax 'flashes' as it appears to refresh for every keystroke (see embedded video).

https://user-images.githubusercontent.com/64705985/150877129-35856215-5e5c-43d7-924e-a68f93d230c8.mp4

### To Reproduce

This problem happens with both long and short documents. It only happens when typing quickly, though I do not type unusually fast.

I tried removing sections from the markdown style format. Removing things like html tags made no apparent difference. However, removing the patterns for headings 1–6 (which are contained under the Types section in the format editing window) significantly reduced the problem (though did not eliminate it entirely).

### Expected behavior

I would like this not to happen! CotEditor is an almost perfect markdown editor but when the highlighted syntax flashes like this, to be honest, it makes me feel nauseous after a while, and writing markdown without syntax highlighting is undesirable.

### CotEditor version

4.0.9 (473)

### macOS version

12.0.1 (Build 21A559)

**Comment by 1024jp** [comment] 2022-02-01 12:10
Thank you for the report.
I reproduced the issue on CotEditor 4.0.9 + macOS 12.1.

I also test it on the latest develop version of CotEditor, and found it seems not happen anymore, maybe because I improved the syntax highlight parsing algorithm.
Honestly speaking, I am not sure it means either this issue was fixed or the just the input interval threshold for flicking shorten.
Anyway, please try the next version, CotEditor 4.1.0, which will be released in this February, when it is released.

**Comment by prc1212** [comment] 2022-02-01 12:21
Thanks. I will look forward to trying the new version.

FWIW, I was able to narrow the problem down to the following lines in the .yaml file:

```
- beginString: .+\n\-+[\t ]*$
  description: h2
  regularExpression: true
- beginString: .+\n\=+[\t ]*$
  description: h1
  regularExpression: true
```

If I comment out those lines, the problem (almost completely) goes away.

**Comment by 1024jp** [comment] 2022-02-02 05:07
Oh, thank you for spotting the cause.
I have also succeeded in speeding up the highlight parsing by improving the syntax definition for Markdown.

**Comment by 1024jp** [comment] 2022-02-15 04:13
CotEditor 4.1.0 addressing this issue was released today. Feel free to let me know if you feel it is still blinky.

**Closed by 1024jp** 2022-02-15 04:13 UTC
Labels: potential bug

**Comment by prc1212** [comment] 2022-02-16 23:40
This is greatly improved in the latest version. Thanks for all your work!
