### ISSUE TITLE
"Reset To Default" font size function is not working

### ISSUE THREAD

**Issue by fiery-** [coteditor/CotEditor#743] opened 2017-10-25 21:03 UTC
I'm using CotEditor 3.2.3 (205). I found these small but annoying problems:
1. In CotEditor the Cmd+= shortcut by default is assigned to the "Reset To Default" font size function. However, this function is not working invoked either through the shortcut or through Format -> Fonts menu. My default font is Menlo Regular 12 set in CotEditor Preferences. 
My suggestion is to assign Cmd+0 shortcut as other apps do (i.e. Firefox, Safari) and check why reset function is not working.

2. The shortcut for a bigger font is Cmd++, but in other apps the Cmd+= also works, since the "+" (plus) key sometimes requires Shift and sometimes not (when using plus in numeric keypad).  However, if I change "Reset To Default" shortcut to Cmd+0, then Cmd+= starts working as expected and makes font bigger.
![Format -> Font menu](https://user-images.githubusercontent.com/4441889/32021510-48f6beaa-b9dc-11e7-9f29-8792199a8bf4.png)

3. In Key Binding Preferences, user can't select Bigger, Smaller font shortcuts. Only the "Reset To Default" option is available. That's not a problem for me, since the Bigger shortcut, was fixed when I changed the Reset shortcut to Cmd+0.
![Key Bindings](https://user-images.githubusercontent.com/4441889/32021552-5a7ceb9a-b9dc-11e7-821f-1555daa21a2b.png)

**Comment by 1024jp** [comment] 2017-10-26 04:24
Thank you for the bug report.

1. It is a bug. I've just fixed it.
2. I confirmed this phenomenon and I also feel it's a bit strange. However, because this is oddly the default behavior of Cocoa for the ⌘+ shortcut, I'll not add special workaround for this.
3. This is actually by design from the very first versions of CotEditor. But, I suppose there is no practical reason to disable customizing those actions. So, I'll change this behavior in the next version.

The fixes will be applied in the next CotEditor 3.2.4, which will be released in early November.

**Closed by 1024jp** 2017-10-26 04:24 UTC
Labels: bug
