### ISSUE TITLE
snippets have gone

### ISSUE THREAD

**Issue by mer60** [coteditor/CotEditor#953] opened 2019-05-01 08:12 UTC
after updating to CotEditor 3.7.2 (may after updating to 3.7.1 -I'm not sure-) all snippets have gone and there is no way to add these or new snippets: it's possible to change the key (e.g. ^0) but I can't insert any text for the snippet

**Comment by mer60** [comment] 2019-05-01 14:07
thank you for your quick response ...
I've made a mistake in version-no's: I'm actual on 3.7.3; so it may happend with 3.7.2 ;-( 
macOS is 10.13.6

**Comment by 1024jp** [comment] 2019-05-01 23:04
Thank you for the additional data and sorry for the issue.
This must be a bug. I succeed to reproduce your issue also under my environment.
Honestly speaking, I'm not sure yet why it occurred because I suppose I didn't modify that part recently.
But anyway, I'll check the code.
It'll be fixed in the next version.

ref. #951

**Closed** 2019-05-12 15:36 UTC
Labels: bug
