### ISSUE TITLE
Pressing "del" key in block-selection mode deletes too much characters

### ISSUE THREAD

**Issue by DerWeiseScheuch** [coteditor/CotEditor#1033] opened 2020-02-18 16:44 UTC
## Steps to Reproduce the Issue 
Consider text of 2 lines:

abcdefg
1234567

Holding down the alt-key (block mode) and using the mouse I select a rectangular block of 6 charcters: abc + 123

Pressing the del-key deletes 8 characters: abcd + 1234

## Expected Result
Pressing the del-key should delete the characters in the selected block. No more, no less.
(compare XCode, Visual Studio, IntelliJ, Notepad++ ...)

**Comment by 1024jp** [comment] 2020-02-20 09:28
Thank you for the feedback.
However, I could not reproduce your issue under my environment.

Could you tell me your macOS and CotEditor versions?
Furthermore, it is helpful if you also share the screencast of the procedure.

**Comment by 1024jp** [comment] 2020-03-02 08:50
No any reply? Or are there other users who faced the same (or a similar) issue?
If there is no reply, then I'll close this issue later.

**Closed** 2020-03-13 00:30 UTC
Labels: bug (works for me), waiting reply
