### ISSUE TITLE
Input field glitches on Find & Replace dialog window

### ISSUE THREAD

**Issue by solidcolour** [coteditor/CotEditor#381] opened 2015-05-05 15:16 UTC
See the screenshot attached. OS X 10.8.5

![screen shot 2015-05-04 at 6 39 30 pm](https://cloud.githubusercontent.com/assets/1742906/7475871/24bcd50c-f318-11e4-9f3b-c6ca1f0054ca.png)

**Comment by 1024jp** [comment] 2015-05-06 01:57
Hmmm, I've received another user report about the same issue also on Mountain Lion before.
But unfortunately, I couldn't reproduce this under my environment even on OS X 10.8.5.
The reporter before told me that this issue occurs randomly and rarely, therefore I suppose it's actually not a bug based on CotEditor but one by OS X System.
However if this happens on multiple users' computers, we should add some workaround.

Questions:
1) Do you always get this broken layout?
2) Please write down if you know how to reproduce this, or it occurs under some specific conditions.

**Comment by solidcolour** [comment] 2015-05-07 13:54
Thanks for the reply. Yes, it happens all the time, I also tried resetting all the preferences, didn't help. it still functions correctly though. Looks like it's just the text Find and Replace overlap with the icons. I don't know what it should look like, but it seems missing the text indent settings, perhaps you could also just get rid of the icons.

**Comment by 1024jp** [comment] 2015-05-17 14:59
Thanks for your answer.
Well, if the bug occurs all the time, it should be fixed somehow.
I'll look into the code later.

**Comment by 1024jp** [comment] 2015-05-28 04:19
Note: According to an another report, this problem occurs also on Yosemite, OS X 10.10.3. Thus, it's not specific on Mountain Lion.

**Comment by 1024jp** [comment] 2015-05-28 04:28
@solidcolour Hey, I have an additional question about this issue.
Could you tell me what happens when you do the following two operations:

1) just resize the find panel.
2) maximize the find panel once, and then resize again it to the previous size.

 Are the input areas still wrong placed after the operation? Or they are fixed.

**Comment by solidcolour** [comment] 2015-05-29 02:21
- Problem disappears after max size and revert to default size. But after quit/reopen the app problem shows up again.

- Problem disappears after resize the box, no problem at all after quit/reopen, amazing!

**Comment by 1024jp** [comment] 2015-06-04 02:20
@solidcolour Thanks for the feedback. It a helpful information!

**Closed** 2015-06-10 06:07 UTC
Labels: bug
