### ISSUE TITLE
quarantine extended attribute gets set on every save using macOS Monterey

### ISSUE THREAD

**Issue by shinepixel** [coteditor/CotEditor#1216] opened 2021-10-17 08:10 UTC
### Description

Every time I save a file, the extended attribute `com.apple.quarantine` gets set for this file:
```
$ xattr -r file.txt|grep quarantine
file.txt: com.apple.quarantine
```
This is especially problematic, when editing scripts, because the script cannot run with the attribute set:
```
$ ./script.sh
-bash: ./script.sh: /usr/bin/env: bad interpreter: Operation not permitted
```

Interestingly when creating and saving a new file, the attribute is not set. It happens only on subsequent saves.

I do have GateKeeper disabled.

`/Applications/CotEditor.app` does not have the attribute.

### To Reproduce

1. Opening any file
2. Saving the file
3. Open Terminal
4. Check for `com.apple.quarantine` extended attribute
5. File has attribute set

### Expected behavior

File should not have extended attribute set

### CotEditor version

4.0.8

### macOS version

12.0 Beta (21A5543b)

**Comment by 1024jp** [comment] 2021-11-17 07:06
I researched this issue and found that the cause is Monterey's system change.
That is, this is a kind of bug by Apple.
For instance, Text Edit.app also have the same issue.
And unfortunately, it is hard to fix by the 3rd party side, because the quarantine extended attribute is one of the security attributes by Apple, which is impossible to edit from CotEditor.
I'll continue trying to find a workaround, but feel it's perhaps better to wait for the fix by Apple.

**Comment by GloryAlex** [comment] 2021-11-29 04:24
I found one thing:
After edit and save a `.command` file by `CotEditor`, MacOS show attention "the script is created by CotEditor and are you sure to run it", like that:
![System attention](https://i.loli.net/2021/11/29/kweOrEM1mYR26uv.jpg)

----
The edit by other editor(e.g., `vscode`) with no such bug has no such attention too.

**Comment by awulf** [comment] 2021-11-29 07:03
I'm experiencing this problem too, making it pretty much unusable to edit bash scripts. 
BBEdit gets around it like this: https://www.barebones.com/support/bbedit/quarantine.html 
Which seems to work

**Comment by rprimmer** [comment] 2021-12-29 21:34
Same issue. I can no longer use CotEditor for any scripting work. :(

The only workaround I've found for editing scripts with CE is to move the script to the /Applications directory. Monterey (12.1) doesn't seem to add to the quarantine attribute on save if the file is in this particular folder. 

Alternatively, you need to use a different editor for script files, such as BBEdit or Xcode.

**Comment by printmaps** [comment] 2022-01-10 12:45
As workaround the quarantine flag ("com.apple.quarantine") can be manually removed:

```
Source file has no flag "com.apple.quarantine":
% xattr -l test2-plasma2.zsh
com.apple.TextEncoding: utf-8;134217984
com.apple.lastuseddate#PS: ?#?a

File edited:
CotEditor (4.0.9) ...

New source has now flag "com.apple.quarantine":
~/Plasma-Art % xattr -l test2-plasma2.zsh
com.apple.TextEncoding: utf-8;134217984
com.apple.lastuseddate#PS: ?#?a
com.apple.metadata:kMDLabel_2v5qwirremarxhxf7pup4w7rim: ?)???;??m????????w???uJ??ѩ՘??I?k
?pXCW?/?E?Z?o~k2@.z+??*???{jMt?
com.apple.quarantine: 0086;61dc2843;CotEditor;

Script no longer working/starting:
./test2-plasma2.zsh       
zsh: operation not permitted: ./test2-plasma2.zsh

Workaround: remove flag "com.apple.quarantine" manually:
xattr -d com.apple.quarantine test2-plasma2.zsh

Script working/starting now:
...

```

**Comment by GameParrot** [comment] 2022-02-01 23:50
Building it without sandbox fixed it for me.

**Comment by 1024jp** [comment] 2022-02-13 05:46
According to my test with macOS 12.3 Beta (21E5206e), this issue will be fixed on macOS 12.3.
Therefore, I do not add extra code to CotEditor for this issue.

**Closed** 2022-03-27 03:47 UTC
Labels: bug,  matter

**Comment by MStraeten** [comment] 2024-01-04 13:13
Issue seems to be back with latest 4.7.2 from apple app store ...

**Comment by 1024jp** [comment] 2024-01-21 02:07
@MStraeten Thank you for the report. However, I could not reproduce the issue. Do you have any specific conditions to reproduce it?
