### ISSUE TITLE
[Request] Jump/Reference Points

### ISSUE THREAD

**Issue by gsingh13** [coteditor/CotEditor#1498] opened 2023-07-12 01:20 UTC
**Is your feature request related to a problem? Please describe.**
I use CotEditor to review device and firmware logs, for QA/debugging purposes. When debugging, I'll usually add comments in-line and start them with a certain phrase as a way to add a reference point for myself to get back to. 
— By the way, I prefer to use CotEditor, due to its find feature, where after tapping “Find All”, all lines & strings show where the searched phrase occurs. 

**Describe the solution you'd like**
It'd be great if: 
1. I could add a “jump” or “reference” point by clicking the line number. Doing so will replace the line number with a dot. 
— This can be further improved by supporting multiple colors that can be added in settings (i.e., click once for yellow, twice for red, etc. &/or click+Y on a line number adds a yellow dot, click+R on a line number adds a red dot, etc.). 

2. A small window opens showing the line number and string for all the jump/reference points added. 

3. When I save the document, the jump/reference points save with it (allowing me to reopen a document in CotEditor to review the points in the future). 

**Describe alternatives you've considered**
As mentioned earlier, currently I manually do this by adding notes/text into a document. 

**Additional context**
N/A

**Comment by gsingh13** [comment] 2023-07-12 18:59
@dimitrik-fr Thanks for the suggestion! How would I add/mark a phrase/text/etc. so that it shows up in the outline menu for a plain text file (if it's possible)?

**Comment by dimitrik-fr** [comment] 2023-07-12 20:33
@gsingh13 -- here is a similar discussion about Bookmarks feature where I also proposed to use Outline with howto example : https://github.com/coteditor/CotEditor/issues/1484#issuecomment-1550270924

let me know if explanation was enough for you, or I can add more details and examples ;-))

personally I found Outline feature in CotEditor as one of the most powerful ones, and giving a great advantage over any similar code/text editors..

**Comment by 1024jp** [comment] 2023-08-15 04:40
Thank you for the request.
As @dimitrik-fr dimitrik already pointed out, your request seems similar to the bookmark feature discussed in #300, #1225, or #1484.
Then, I can say that has been already put in my TODO list. The issue is only the time resource and priority (sorry, but I cannot do everything at once).
I close this ticket due to duplication but that does not mean your request is rejected.

**Closed by 1024jp** 2023-08-15 04:40 UTC
Labels: request
