### ISSUE TITLE
Navigation bar state persistence is buggy

### ISSUE THREAD

**Issue by LeoNatan** [coteditor/CotEditor#1726] opened 2024-09-26 06:07 UTC
### Description

Hello,

There is a bug in navigation bar persistence (introduced in the last version, I think).
I have it always off, but recently, it seems to be always on, and the menu item state is broken; it says “Hide Navigation Bar”. Selecting that menu item does nothing. Selecting it again hides the navigation bar, but quitting and relaunching the app does not persist the state.

Eventually, it got persisted, but now the opposite is true, where there is a “Show Navigation Bar” menu item that does nothing on the first selection, and persistence is once again broken.

### To Reproduce

Described above.

### Expected behavior

Menu item should always work, state should be reflected correctly in the menu item, and state should be correctly persisted across new window opening and app relaunch.

### CotEditor version

5.0.1

### macOS version

15.1 Beta (24B5055e)

**Comment by 1024jp** [comment] 2024-09-26 08:31
Thank you for the report.

As you pointed out, this is a bug in the latest version. Sorry.
The issue is already fixed in the code base #1724 and the fix will be shipped with CotEditor 5.0.2.

**Closed by 1024jp** 2024-09-26 08:31 UTC
Labels: bug, duplicate
