### ISSUE TITLE
Wrong text colorisation when using '#' in php code

### ISSUE THREAD

**Issue by hwiesmann** [coteditor/CotEditor#879] opened 2018-12-03 19:44 UTC
This code is wrongly colorised (CotEditor assumes that '#' starts a comment):

`<?php
	echo '<div style="color:#00ff00"></div>';
?>`

**Comment by 1024jp** [comment] 2018-12-14 05:32
Close this issue because of #619, which is actually caused by the same underlining comment extracting procedure.

**Closed by 1024jp** 2018-12-14 05:32 UTC
Labels: better to fix
