### ISSUE TITLE
Status bar drawing collapses on Coteditor 3.0.2

### ISSUE THREAD

**Issue by miltar** [coteditor/CotEditor#622] opened 2016-10-17 17:06 UTC
This comes together with the new update.
![captura de pantalla 2016-10-17 a las 19 02 50](https://cloud.githubusercontent.com/assets/2460634/19447186/a8765ad6-949c-11e6-8d52-b5ad8e11a4e5.png).
 Thanks

**Comment by miltar** [comment] 2016-10-17 17:08
Sorry, It happens when I launch the editor, but if I remove and return to add details from preferences, it fixes. If it helps anything.

**Comment by 1024jp** [comment] 2016-10-17 17:10
Umm, that's strange.
Does it occur even you restart whole Mac OS?
If yes, please tell me your OS version.

**Comment by 1024jp** [comment] 2016-10-17 17:16
Ah, ok, then tell me if it reproduced again.

Otherwise I'll close this issue 1 week later.

**Comment by 1024jp** [comment] 2016-10-17 17:19
Oups, I've just found the reason of this collapsing. This is a bug. Thank you for your report. I'll fix this on the next version.

**Closed** 2016-10-17 17:34 UTC
Labels: bug

**Comment by miltar** [comment] 2016-10-17 18:33
Thank you...Good Work!!
