### ISSUE TITLE
Selecting lines with shift+cursor gets confused with line-wrap

### ISSUE THREAD

**Issue by gingerbeardman** [coteditor/CotEditor#1585] opened 2024-01-27 15:20 UTC
### Description

Selecting lines with shift+cursor gets confused after it encounters a line that is wrapped

### To Reproduce

1. Load a file with some long lines, eg. source code
2. Activate line wrap and/or split window vertically
3. Use shift+cursor to select line at a time
4. Cursor selects parts of lines after it encounters line wrap

### Expected behavior

- should continue selecting full lines regardless after line wrap is encountered

### CotEditor version

- 4.7.3

### macOS version

- 14.3

### Additional context

Screen recording

https://github.com/coteditor/CotEditor/assets/49612/fed42210-ace1-46c2-897a-8a6f3d6a985e

**Comment by 1024jp** [comment] 2024-01-28 14:15
I'd say it is currently by design that the hanging indentation part is not highlighted when selecting.
But, I understand it feels odd.

I'll check whether there is a lightweight way to detour it.

**Comment by gingerbeardman** [comment] 2024-01-28 15:49
Well, there are two things happening:
1. not selecting hanging part of line (normal, expected)
2. beyond the hanging part selection is no longer working in full lines (bug, unexpected)

For item 2, I tested all my other editors and none of them operate this way.

- BBEdit
- TextMate
- Sublime Text
- SubEthaEdit
- Nova

**Comment by 1024jp** [comment] 2024-02-10 14:49
Aha, OK. Now I understand the second issue. Let me see if I can fix it.

**Comment by gingerbeardman** [comment] 2024-02-10 16:24
Thanks, sorry that my description was not very good.

**Comment by gingerbeardman** [comment] 2024-12-09 16:05
Still happening in 5.0.6

**Comment by 1024jp** [comment] 2024-12-12 04:14
Yes. I haven’t begun working on this issue yet.
I intend to do so, but the character selection process is intricate, therefore I prefer to tackle it when I have ample time.

Note: this happens only when the line endings are CRLF. So it is a minor issue.

**Comment by 1024jp** [comment] 2024-12-13 14:29
Fixed on the next version 😉.

**Closed** 2024-12-13 14:28 UTC
Labels: better to fix

**Comment by gingerbeardman** [comment] 2024-12-15 15:11
Love it 🙌

Thank you
