### ISSUE TITLE
Cursor position gets incorrect when breaking a line in itemization

### ISSUE THREAD

**Issue by hidetatz** [coteditor/CotEditor#1327] opened 2022-06-28 09:40 UTC
### Description

When I am editing a itemizing text and break a line, the cursor position is automatically adjusted with the above line. However, when there are 4 or more head spaces as the indentation and try to add spaces more, the cursor position gets incorrect.

I recorded a screencast.

https://user-images.githubusercontent.com/60682957/176146920-c5002698-332c-485b-9ea8-d8a13eeb1d0c.mov

### To Reproduce

1. Open a new tab or window.
2. Insert `- aaa` and press return key.
3. Press space key 4 times, then insert `- bbb` . As of here, nothing is wrong. Press return key.
4. Press space key 4 times. At the fourth press, the cursor key gets the wrong position.

### Expected behavior

The cursor positon should not move to the line head unexpectedly.

### CotEditor version

4.3.0

### macOS version

macOS Big Sur 11.6.4

**Comment by 1024jp** [comment] 2022-06-28 13:16
Thank you for the report.
However, I could not reproduce your issue even following the procedure you described.

In order to determine the cause, could you post the screenshots of the following setting panes?
- General
- Appearance
- Edit

In addition, it seems like your issue is something related to #1326. Can you also reproduce the situation described in #1326 with your environment?

**Comment by hidetatz** [comment] 2022-06-29 03:13
Thank you for your response. I attached the screenshots you requested.

![general](https://user-images.githubusercontent.com/60682957/176343259-fc416923-0e2b-44c9-8dea-8515cbdd1cde.png)


![appearance](https://user-images.githubusercontent.com/60682957/176343228-ec5c97a7-373f-4b78-b837-3462ebfd8f6a.png)

![edit](https://user-images.githubusercontent.com/60682957/176343267-7ef911f7-5dc1-47e1-9fd4-5c08eac468ae.png)


In addition, I could not reproduce #1326 on my side.

**Comment by 1024jp** [comment] 2022-06-29 04:00
Thank you for the additional information.
Now I succeed in reproducing this behavior.
Let me have  time to fix.

**Comment by 1024jp** [comment] 2022-06-29 04:03
I found the key is the font. When you change the font for the editor from Noto Sans JP to other one, the cursor moves correctly.

**Comment by 1024jp** [comment] 2022-06-29 04:17
I found this phenomenon occurs also in TextEdit.app by Apple.
Thus, it is a bug either by Apple or the font for that CotEditor has no responsibility.
So, I understand the issue exists but let me close this ticket.

https://user-images.githubusercontent.com/1165044/176350019-a457ed0b-52e8-440e-b715-0034f16a4478.mov

**Closed by 1024jp** 2022-06-29 04:17 UTC
Labels: better to fix,  matter

**Comment by 1024jp** [comment] 2022-06-29 04:31
Filed: FB10498439

**Comment by hidetatz** [comment] 2022-06-29 09:03
I also confirmed this does not occur if I use another font. Thank you for your effort!
