### ISSUE TITLE
problem with invoking CotEditor from a remote Terminal

### ISSUE THREAD

**Issue by mibuzzi** [coteditor/CotEditor#1018] opened 2020-01-09 15:28 UTC
Our IT consists of terminal sessions from clients on our local server. 
To be able to edit files on the server in a comfortable way we send the file to the client with scp, edit it locally with CotEditor sshing following command:
ssh -q mb@imac-mb.local -t '/Applications/CotEditor.app/Contents/SharedSupport/bin/cot --wait file.txt'
and then scp the file back on the server.

Normally this works perfect but in some cases and on some Laptops we get this error message:

File "/Applications/CotEditor.app/Contents/SharedSupport/bin/cot", line 411, in <module>
    main(args, stdin)
  File "/Applications/CotEditor.app/Contents/SharedSupport/bin/cot", line 330, in main
    app.open(path)
  File "/Applications/CotEditor.app/Contents/SharedSupport/bin/cot", line 161, in open
    self.tell('open POSIX file "{}"'.format(path), is_async=True)
  File "/Applications/CotEditor.app/Contents/SharedSupport/bin/cot", line 141, in tell
    raise error
subprocess.CalledProcessError: Command 'ignoring application responses
tell app "/Applications/CotEditor.app" to open POSIX file "/Users/mb/e_tpc.kal"
end ignoring' returned non-zero exit status 1

**Comment by 1024jp** [comment] 2024-12-14 15:50
Sorry for the omission in my reply since I was unable to reproduce your issue at the time.
It has been a long time since this post and the specifications of CotEditor and macOS have changed, so please let me close this ticket for now.
If the issue persists, please let me know, and I’ll reopen it accordingly.

**Closed by 1024jp** 2024-12-14 15:50 UTC
