### ISSUE TITLE
Can't set font in 10.13

### ISSUE THREAD

**Issue by zieglar** [coteditor/CotEditor#732] opened 2017-10-06 06:11 UTC
set font don't work

**Comment by 1024jp** [comment] 2017-10-06 08:23
It works for me.

Please fill the following template:

```

## Environment

- CotEditor: 
- System: macOS Version 10.13
- Language: ?


## Short Description

<!-- put your comment here -->


## Steps to Reproduce the Issue

<!-- put your comment here -->


## Expected Result

<!-- put your comment here -->

```

**Comment by zieglar** [comment] 2017-10-06 09:07
## Environment

- CotEditor: 3.2.2 (203)
- System: macOS Version 10.13
- Language: zh_CN


## Short Description
can't set font to other font, still Helvetica 13

## Steps to Reproduce the Issue
in Appearance preferences change font select but no effect.

## Expected Result
change Helvetica to other font

**Comment by 1024jp** [comment] 2017-10-08 00:58
Thanks for the additional info.
However, I still can not reproduce this issue.

Is there anyone who is facing this issue?

**Comment by tatsy-ymj** [comment] 2017-10-11 05:43
I got the same phenomenon.

1. Push "Select..." button and Font Dialogbox appears.
2. If I input font size manually, the status of the dialogbox wan't reflected. If I choose font size from listbox or scrollbar, it works.

**Comment by 1024jp** [comment] 2017-10-14 03:34
@tatsy-ymj
Thank you for the another information.
Following your instruction, I could reproduce the phenomenon.

I may be able to fix the issue on the next CotEditor, which will be released soon (next week?).
Thank you @zieglar for the bug report.

**Closed** 2017-10-14 04:34 UTC
Labels: bug
