### ISSUE TITLE
[Multiple Cursors] Selections next to each other merge

### ISSUE THREAD

**Issue by huyphams** [coteditor/CotEditor#987] opened 2019-09-29 00:20 UTC
- If you select a string like: `aa aaaa aaaaaaa`
Command + D (1st) => select range `aa` => wrong, it should be `a` and `a`
Command + D (2st) => select range `aa` and `aa` => wrong, it should be `a` and `a` and `a`
....
The demonstration gif:
![2019-09-28 21 14 53](https://user-images.githubusercontent.com/3654622/65823901-80967980-e235-11e9-9396-5610ceb940a8.gif)

The expected behavior in Sublime Text:
![2019-09-28 21 19 11](https://user-images.githubusercontent.com/3654622/65823908-a754b000-e235-11e9-8521-e41039bd808e.gif)

**Comment by 1024jp** [comment] 2019-09-29 01:53
Thank you for the feedback.
However, this behavior is currently the limitation of TextKit, on which the CotEditor's editor area depends.
It would be better to fix, but actually hard.
Sorry about that.

**Comment by huyphams** [comment] 2019-09-29 01:55
No worries @1024jp let me try to fix it.

**Comment by 1024jp** [comment] 2019-09-29 02:51
@huyphams That would be great!

**Comment by 1024jp** [comment] 2020-02-23 04:13
I close this request because there is regretfully almost no chance to implement it as long as CotEditor uses TextKit. It is by design.

**Closed by 1024jp** 2020-02-23 04:13 UTC
Labels: better to fix
