### ISSUE TITLE
(Question) is the "quit coteditor when there are no open windows" feature removed ? ☹️

### ISSUE THREAD

**Issue by fokusuma** [coteditor/CotEditor#1453] opened 2023-03-13 02:08 UTC
### Description

hi coteditor devs, thanks for the great update. in previous version (I'm forget which version it is), I'm able to set coteditor closed when no window is open, but no luck in this version, do i miss something ? 

### To Reproduce

i don't think its a bug

### CotEditor version

4.4.5

### macOS version

13.2.1

**Comment by 1024jp** [comment] 2023-03-13 03:28
Thank you for the report!

CotEditor doesn't have an option for the automatic termination but designed always to terminate itself when no documents exist and the application goes background.
However, after your report, I realized the feature was accidentally removed in a past version.

I've fixed it for the next version, CotEditor 4.5.0, which will be released late this month.
Sorry for inconvenience for a while.

**Comment by fokusuma** [comment] 2023-03-13 03:39
thanks @1024jp can't wait for the update 🎉

**Closed** 2023-03-13 03:57 UTC
Labels: bug

**Comment by I7T5** [comment] 2023-05-12 10:00
I don't think I have this feature in version 4.5.5. Tried closing my window a multitude of times, and check everywhere in the settings. Did I miss something?? macOS 13.3.1 (a)

**Comment by 1024jp** [comment] 2023-05-16 01:13
1. CotEditor will terminate first when it has no document windows __and it goes to background__ (namely, another application becomes the frontmost one).
2. Even so, CotEditor will not terminate when the system has enough memory. This is by design.
