### ISSUE TITLE
Cannot scroll until the end of the contents

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#736] opened 2017-10-11 07:13 UTC
It seems that CotEditor 3.2.2 can't handle big text files properly.

macOS 10.13

1. Open a big text file. (approximately more than 40000 Japanese characters or so)
2. Scroll down the text. It can't display after a certain line. However, it can jump to the end of the file. 
3. Go back to the top of the file, and then it can display whole text with scrolling.

[test.md.zip](https://github.com/coteditor/CotEditor/files/1374526/test.md.zip)
https://drive.google.com/file/d/0B0emCo_bF-igVjlKSkhnUVdoM0k/view?usp=sharing

**Comment by 1024jp** [comment] 2017-10-14 06:06
Thank you for the bug report.
I succeed in reproducing the issue with your sample file.
(Such a sample file helps a lot for the debug. I appreciate you ❤️)

This phenomenon may be a kind of side-effect of the Cocoa's non-continuous layout feature, which is provided by Apple to reduce the calculation time of large text content layout.
Therefore, fixing this may take a longer time to open a large file.
But anyway, the current situation is not good. I'll try to fix.

**Comment by 1024jp** [comment] 2017-10-14 06:48
cf. #680

**Comment by 1024jp** [comment] 2017-10-22 14:27
I've added a small tweak around the editor view layout to CotEditro 3.2.3, which was released today.
However, I'm not sure if your issue was fixed, because I can't reproduce it anymore under my environment.
Please let me know and reopen this issue, if you still have the same issue on 3.2.3.

**Comment by 1024jp** [comment] 2017-11-02 05:53
I once reopen this issue as I realized by issue #742 that the issue still exists on CotEditor 3.2.3.

**Comment by 1024jp** [comment] 2017-11-05 02:17
I realized this bug is not caused by CotEditor's code but a bug of High Sierra by Apple because the same issue can appear on other applications like Espresso.app or the Quick Look of general plain-text files (cf. [user report](https://twitter.com/dy4_268/status/925930462622597120)).
Moreover, this might be a bug related to the non-contiguous layout feature of NSTextView.

Hence, I can do actually nothing to fix this bug. However, at the same time, I understand this is kind of critical issue for a text editor. So, I added a workaround for this bug to __CotEditor 3.2.4__, which is released today, disabling the non-contiguous layout feature temporary until the origin bug is resolved ([release notes](http://coteditor.com/releasenotes/3.2.4.en)).

The timing to close this issue is when Apple fixes it. I keep this issue open til the day.

**Comment by 1024jp** [comment] 2017-11-06 07:25
cf. [High Sierraにアップデート後、テキストファイルが最後まで読み込めなくなってしまいました。-Apple Official Support Community](https://discussionsjapan.apple.com/thread/110194333?start=0&tstart=0)

**Comment by 1024jp** [comment] 2018-03-31 10:59
I've enabled the non-contiguous layout feature at 311c6192af8b1453177e572d121adbbaec640676 on CotEditor 3.4.0.
I'd like to test it while beta versions for 3.4.0 and ship with the stable 3.4.0 if I can confirm that this issue doesn't exist anymore on the latest macOS (10.13.4).

**Closed by 1024jp** 2018-03-31 10:59 UTC
Labels: better to fix,  matter
