### ISSUE TITLE
Bug in CotEditor 2.5.4: ⌘+N doesn’t focus the content area of a new file

### ISSUE THREAD

**Issue by handcoding** [coteditor/CotEditor#557] opened 2016-05-13 19:33 UTC
In CotEditor 2.5.4, when you start a new file, the content area isn’t focused. Which makes it harder to use CotEditor solely with a keyboard.

Here’re the steps to reproduce:
1. Open or focus CotEditor.
2. Press ⌘+N to start a new file.
3. Start typing anything.

* Current results: The letters that you type don’t appear in the new document. (You first have to click on the new document’s content area—then you can type.)
* Expected results: The letters that you type appear in the new document.

(From what I can tell, I think this can be resolved by focusing the content area when a new file is started.)

**Comment by 1024jp** [comment] 2016-05-14 03:13
That's a bit weird since it works fine under my conditions.

To identify the cause, could you tell me the followings?:

1. Version of OS X
2. Did this issue exist already on CotEditor 2.5.3 or started just on 2.5.4 (, or you didn't try 2.5.3)?
3. Does it happens only with new documents? (How about if you open a existing file.)

**Comment by 1024jp** [comment] 2016-05-15 13:01
I've received a report of the same issue from another user.

> ## Environment
> 
> - CotEditor: 2.5.4 (127)
> - System: OS X Version 10.11.4 (Build 15E65)
> - Language: English
> 
> 
> ## Short Description
> 
> WhenI open not only a new window (as "hardcoding" reported at GitHub)
> but any existing file, the content area is not focused, or a cursor
> does not appear in the window (the first line is marked, i.e., it may
> be the current line). I have to use trackpad and click the window area
> to start editing.
> 
> ## Steps to Reproduce the Issue
> 
> Always when you start the editor.

**Comment by handcoding** [comment] 2016-05-15 15:18
I’m sorry I didn’t reply earlier. Here’re my answers to your questions:

> Version of OS X

I’m on 10.11.4.

> Did this issue exist already on CotEditor 2.5.3 or started just on 2.5.4 (, or you didn't try 2.5.3)?

Although I briefly upgraded to 2.5.3 when it came out, I soon reverted back to the previous version of CotEditor because of the word-wrapping bug (#551).

> Does it happens only with new documents? (How about if you open a existing file.)

Yup—it happens when I open an existing file too.

**Comment by handcoding** [comment] 2016-05-15 15:24
If it may help, here’re each of CotEditor’s preference dialogs as I have them set:

![coteditor 2-5-4 - general](https://cloud.githubusercontent.com/assets/118319/15275031/b08aa924-1a86-11e6-8e6d-ee9bbf746f7c.png)
![coteditor 2-5-4 - window](https://cloud.githubusercontent.com/assets/118319/15275039/d7833776-1a86-11e6-84a0-2c9621495c08.png)
![coteditor 2-5-4 - appearance](https://cloud.githubusercontent.com/assets/118319/15275040/e0c74322-1a86-11e6-8a90-ca32916efe2b.png)
![coteditor 2-5-4 - edit](https://cloud.githubusercontent.com/assets/118319/15275041/e9973a02-1a86-11e6-94fc-8b1716f91fe5.png)
![coteditor 2-5-4 - format](https://cloud.githubusercontent.com/assets/118319/15275042/f15fbebc-1a86-11e6-82d5-035df5be6ac1.png)
![coteditor 2-5-4 - file drop](https://cloud.githubusercontent.com/assets/118319/15275043/f9df8cc0-1a86-11e6-81a8-c1e94ac18a9a.png)

(I figure that the prefs for Key Bindings, Print, and Integration probably aren’t relevant, so I haven’t included those. Although having said that, if you might like me to post screenshots of those too, I can certainly do so.)

**Comment by 1024jp** [comment] 2016-05-15 16:25
@handcoding 
Thanks for sharing such super useful screenshots. They are actually what I wanted to know.
However unfortunately, even with this information, I can't reproduce the issue yet :-/
But, now, I have an idea in my mind why it cause on 2.5.4. So probably I may be able to fix it on the next version that will be released in the next month.

**Closed** 2016-05-16 14:54 UTC
Labels: bug

**Comment by handcoding** [comment] 2016-05-16 15:08
> But, now, I have an idea in my mind why it cause on 2.5.4. So probably I may be able to fix it on the next version that will be released in the next month.

Fantastic!

And I don’t mean to be a bother, but just out of curiosity, can I ask what happened to cause the bug?

**Comment by 1024jp** [comment] 2016-05-20 18:33
> And I don’t mean to be a bother, but just out of curiosity, can I ask what happened to cause the bug?

I actually skipped a process to force focusing on the editor area on the window generation in 2.5.4, because it seemed that the app still focuses on the editor, well..., at least under my environment. It was wrong. I've restored the process in the next version so that it (may) behave as like before.

**Comment by handcoding** [comment] 2016-05-23 15:17
By the way, I can confirm that this is fixed in CotEditor 2.5.5. 👍🏼

**Comment by 1024jp** [comment] 2016-05-23 15:58
Thanks for your confirmation. I'm relieved to hear that 😊
