### ISSUE TITLE
`この新しい書類"名称未設定"を残しますか？` ダイアログ最下部をマウスで操作できない

### ISSUE THREAD

**Issue by ngsw** [coteditor/CotEditor#1313] opened 2022-05-24 04:46 UTC
### Description

- `この新しい書類"名称未設定"を残しますか？` ダイアログ最下部をマウスで操作できない

### To Reproduce

- cmd + w で編集中のwindowをクローズするとき、 `この新しい書類"名称未設定"を残しますか？` というダイアログがでるが、マウス操作で `削除` や `キャンセル` を選択押下できない
- キーボードの Tab と Space で選択自体は可能

### Expected behavior

- マウス操作で `削除` や `キャンセル` を選択押下できること

### CotEditor version

4.2.1 (505)

### macOS version

macOS バージョン12.4（ビルド21F79）

### Additional context

![coteditor](https://user-images.githubusercontent.com/159474/169950948-758e4cd1-173f-436a-a4c6-2d454b2e098c.gif)

**Comment by 1024jp** [comment] 2022-05-24 05:15
Thank you for the report. This strange behavior seems to occur only on macOS 12.x with Japanese localization and currently, we have no idea to avoid it. I suppose something going wrong on the system side that Apple has the responsibility for.
I'll look into it later again. But sorry, therefore, I cannot promise it will be fixed quickly.

**Comment by ngsw** [comment] 2022-05-26 03:27
I was able to avoid this problem by changing the system language from Japanese to English as per your advice!
![Screen Shot 2022-05-26 at 11 59 53](https://user-images.githubusercontent.com/159474/170409924-45a0b809-a8ba-4b2c-8ee3-c92d1556ea68.png)

**Comment by 1024jp** [comment] 2022-07-12 05:01
Because multiple users claimed this phenomenon occurs outside of CotEditor as well, such as Keynote, I guess this is a bug in macOS. I'll report it to Apple later.

**Comment by nasuadachi** [comment] 2022-07-18 07:29
macOS12 can be changed per app
Click on the Applications tab,(not the General tab)
Press +.
Change CotEditor to English, etc.

**Comment by 1024jp** [comment] 2022-08-11 06:52
Please let me know if anybody knows how to reproduce this issue constantly.

**Comment by 1024jp** [comment] 2022-08-11 09:04
In addition, could you somebody check whether this issue still exists on macOS 12.5 (in Japanese environment)? If so, I'd like to know also that your computer is Intel or Apple Silicon.

**Comment by 1024jp** [comment] 2022-08-13 03:59
Sorry, I closed wrong issue.

**Comment by 1024jp** [comment] 2022-09-04 07:24
Because there is no new report since the release of macOS 12.5, I mark this issue as resolved. If you still have issues, let me know.

**Closed by 1024jp** 2022-09-04 07:24 UTC
Labels: bug, awaiting reply,  matter
