### ISSUE TITLE
Recent items include empty/null entries

### ISSUE THREAD

**Issue by fxcoudert** [coteditor/CotEditor#1556] opened 2023-12-07 10:19 UTC
### Description

The File > Recent list of entries has blank/empty entries:

<img width="702" alt="Capture d’écran 2023-12-07 à 11 15 42" src="https://github.com/coteditor/CotEditor/assets/1980544/38ce21dd-cc7d-4814-94bd-12a336b2f42c">

When I click on them, the entry is `(null)`:

<img width="416" alt="Capture d’écran 2023-12-07 à 11 17 37" src="https://github.com/coteditor/CotEditor/assets/1980544/59e5e33b-96c1-436a-92de-1a1da913123f">

### To Reproduce

1. Go to File menu
2. Click on Recent files
3. See error

### CotEditor version

Version 4.6.5 (601)

### macOS version

14.1.2 (23B92)

**Comment by 1024jp** [comment] 2023-12-10 08:16
Thank you for the report. It's actually one of the long-standing issues...
I'll digg it again in the new year holidays.

**Comment by 1024jp** [comment] 2024-05-12 03:28
I improved several points regarding this issue including the latest CotEditor 4.8.3.
So, now I’d like to know again if the issue still exists in the latest environments.

In my understanding, the following case is exceptionally in spec (by Apple) in that the recent items are cleared when you switch CotEditor between the App Store version, non-App Store version, and development version.
(Therefore, it is difficult for me to reproduce the issue...)
If your issue is not in this case, it would be a bug.

**Comment by 1024jp** [comment] 2024-06-01 14:16
I will close this issue since there seem to be no reports of issues with the latest versions.
If you face a similar issue with a future version, please make a new one.

**Closed by 1024jp** 2024-06-01 14:16 UTC
Labels: bug, awaiting reply
