### ISSUE TITLE
Problem about running scripts on CotEditor 4.0.0

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#1112] opened 2020-10-14 06:56 UTC
- CotEditor 4.0.0 beta 2
- macOS 10.15.7
- MacBook Pro 13 (2017)

I have a trouble about running scripts on CotEditor 4.0.0.

- Some scripts which have no problem on 3.9.6 can't run properly.
- For example, the following is a script which concatnates  selected lines.

```
#!/usr/bin/env ruby -Ku
#%%%{CotEditorXInput=Selection}%%%
#%%%{CotEditorXOutput=ReplaceSelection}%%%

text = ""
while line = $stdin.gets
  if line =~ /^[　 ■【>]/
  	text = text + line
  elsif line =~ /^$/
    text = text
  else
  	text = text.chomp + line
  end
end
print text
```

- When the number of selected lines is more than 10000 or so, it can't work properly. Sometimes it works, but sometime it doesn't.
- Other scripts have the same symptoms.
- When I downgrade CotEditor from 4.0.0 to 3.9.6, there is no problem. All scripts works properly.

**Comment by 1024jp** [comment] 2020-10-14 07:45
Thank you for the report.

What does _"can't work properly"_ exactly mean?
No reaction at all (I guess this), or something else?

**Comment by tatsy-ymj** [comment] 2020-10-14 11:40
Sorry for my insufficient explanations.

> No reaction at all (I guess this)

That's it!

**Comment by 1024jp** [comment] 2020-10-14 12:16
Thank you for the additional info.

Then, I maybe succeed in fixing it. The change will be shipped with the next beta, v4.0.0-beta.3.
So please test it when released (I plan to release the next beta within this week).

**Comment by tatsy-ymj** [comment] 2020-10-20 09:56
I tested CotEditor 4.0.0 beta 3.
It seems better than beta 2. However, it still has problems.

1. For example, apply the following script (it uses pandoc command) from script menu to texts (2000 lines or so).
```
#! /bin/sh
#%%%{CotEditorXInput=AllText}%%%
#%%%{CotEditorXOutput=Pasteboard}%%%
cat - | /usr/local/bin/pandoc -f markdown+hard_line_breaks -t html
```

2. The first time  it works well, but when it is used several times, it doesn't work (no reaction at all).

**Comment by 1024jp** [comment] 2020-10-21 06:54
Ok, thank you for checking beta 3.
It seems I need to reopen this issue and add another measure.
Well, I have an idea, though it takes time to implement. I'll try it first and then release another beta.

**Comment by 1024jp** [comment] 2020-10-24 12:55
Hi. I've just released beta.4 that addressed this issue.
I hope it is perfectly fixed this time...

**Comment by tatsy-ymj** [comment] 2020-10-25 03:08
I checked beta4.
It seems to have a problem.

1. I applied the following script to selected texts on 3.9.7.
```
#!/usr/bin/env ruby -Ku
#%%%{CotEditorXInput=Selection}%%%
#%%%{CotEditorXOutput=ReplaceSelection}%%%

text = ""
while line = $stdin.gets
  print "*" + line + "*"
end
```

<img width="594" alt="スクリーンショット 2020-10-25 11 50 47" src="https://user-images.githubusercontent.com/4995795/97097927-545c5f00-16ba-11eb-8725-1d57eb910ed2.png">

↓

<img width="594" alt="スクリーンショット 2020-10-25 11 50 57" src="https://user-images.githubusercontent.com/4995795/97097936-6fc76a00-16ba-11eb-8b04-0fc287f43e7f.png">

2. I applied the same script on 4.0 beta 4.

<img width="575" alt="スクリーンショット 2020-10-25 11 51 53" src="https://user-images.githubusercontent.com/4995795/97097944-8cfc3880-16ba-11eb-93da-44ae6e50cf14.png">

↓

<img width="994" alt="スクリーンショット 2020-10-25 11 52 25" src="https://user-images.githubusercontent.com/4995795/97097948-95ed0a00-16ba-11eb-9a8c-736ad90ee398.png">

**Comment by 1024jp** [comment] 2020-10-25 11:14
😩 Thank you!

**Comment by 1024jp** [comment] 2020-10-25 12:35
And I've just released a new beta addressing this issue.

**Comment by tatsy-ymj** [comment] 2020-10-25 14:10
It seems scripts work well on beta 5. Thanks!

...However, maybe another problem occurs.

When CotEditor opens a markdown text file without line feeds (10000 characters or so), it takes too much time and CPU power. It seems CotEditor tries to extract syntax coloring.

**Comment by 1024jp** [comment] 2020-10-26 00:12
Thank you for confirming.

> When CotEditor opens a markdown text file without line feeds (10000 characters or so), it takes too much time and CPU power. It seems CotEditor tries to extract syntax coloring.

It sounds like relating to #1111.
Does it first appeared in the beta.5, or already existed prior to beta.5, such as the first beta?
I also interested in how about CotEditor 3.9.7, the current latest stable version.
If the performance was changed from beta.4 to beta.5, I'd like to know if you make your editor opacity non-opaque.
Anyway, I guess this is not related to syntax coloring but character rendering. (However, as for Markdown syntax, it can be also...) Well, I'll

**Comment by tatsy-ymj** [comment] 2020-10-26 07:47
Sorry, it's my mistake.
The problem about syntax coloring occurs both on 3.9.7 and 4.0.0 beta 5.
I mixed up test files...

**Comment by 1024jp** [comment] 2020-10-26 11:23
Thank you for the follow-up.
Then, I'd regrettably say it's by design.
In order to parse Markdown, finding line breaks is required and it causes your issue; because in CotEditor, only the regular expression is used for syntax parsing.
Improving syntax highlighting definition would be able to reduce the calculation time, but parsing Markdown only with regex is already hardcore...

Well, I close this ticket since the original issue is now fixed. Thank you for your patient help.

**Closed by 1024jp** 2020-10-26 11:23 UTC
Labels: bug
