### ISSUE TITLE
Remove Blank Lines

### ISSUE THREAD

**Issue by kre2018** [coteditor/CotEditor#960] opened 2019-05-22 14:01 UTC
## Environment

- CotEditor: 3.7.4 (351)
- System: macOS Version 10.14.5 (Build 18F132)
- Language: English

## Steps to Reproduce the Issue

<!-- use the following code: 
```tell application "CotEditor"
	   activate
	   tell front document
		   replace for "^(\\n|\\s{1,}\\n)" to "" with all and RE
	   end tell
   end tell
``` -->


## Expected Result

<!-- This regex code supposed to remove all lines that are blank regardless if they consist of spaces or just a return (¶) -->

**Comment by 1024jp** [comment] 2019-05-22 15:48
Please write more in detail.
Otherwise, I have to close this issue due to unclear issue formulation.

**Comment by kre2018** [comment] 2019-05-23 02:49
Sure.
Basically I am desiring for a command where “Delete Duplicates” and the rest commands under the Text | Lines menu live.
I am calling that new imaginary command “Delete Blank Lines”. But because that command doesn’t exit I am trying to achieve the same result either by using Find-Replace dialog box or via AppleScript from the Script folder accessible via CotEditor’s Automation menu.
So for example if I use the regex “^(\n|\s{1,}\n)” in the Find-Replace dialog box then there is no problem at all. CotEditor performs excellent.
But if I create a file with extension .scpt and place it in CotEditor’s Automation folder and with the following contents:
tell application "CotEditor"
	activate
	tell front document
		replace for "^(\\n|\\s{1,}\\n)" to "" with all and RE
	end tell
end tell
Then I don’t get the expected result.
So I am asking for help with AppleScript code if there is something wrong.
Ultimately I will be more happy if that “Remove Blank Lines” exist under the Text | Lines menu.
Please let me know if the formulation of my issue clear enough now. If not I can try again. 


On May 22, 2019 at 11:48:25 AM, 1024jp (notifications@github.com) wrote:

Please write more in detail.
Otherwise, I have to close this issue due to unclear issue formulation.

**Comment by 1024jp** [comment] 2019-06-12 03:53
Sorry for my late reply.
I confirmed your issue under the latest version.

This issue arises because regarding the regular expression via AppleScript anchors (such as `^`) doesn't match lines. This inconsistency of the regex between via the Find panel and AppleScript must be solved anyway. I'll fix it in the next version.

**Closed** 2019-06-12 08:05 UTC
Labels: bug, request

**Comment by kre2018** [comment] 2019-06-12 16:56
Fantastic!
Thanks a lot. 
Kind Regards, KK
