### ISSUE TITLE
Mouse click does not work in delete confirmation dialog

### ISSUE THREAD

**Issue by faiare** [coteditor/CotEditor#1377] opened 2022-10-03 02:52 UTC
### Description

Opens a new editor window.
When closing the window or exiting the application after making any edits, a delete confirmation dialog will appear.
Mouse actions do not work on this dialog.
Keyboard actions work fine (e.g., Tab, Space, Esc).

![スクリーンショット 2022-10-03 11 24 02](https://user-images.githubusercontent.com/11206952/193491937-69cac858-f66c-4e91-a94f-b324ff324843.png)

### To Reproduce

1. Go to 'ファイル > 新規'
2. Make any edits
3. Close window or exit application
4. Show delete confirmation dialog

### CotEditor version

4.3.6 (530)

### macOS version

12.6

### Additional context

It may be the same as the following problem fixed in 4.3.5.

> 4.3.5 (529)
> Address an issue since macOS 12.4 that the buttons in the save dialog became occasionally unresponsive when the application is running in some specific Japanese environment.

**Comment by 1024jp** [comment] 2022-12-03 03:25
Thank you for the feedback and sorry for my late reply.
This must be a bug on the Apple side and occurs under particular conditions (I could rarely reproduce this in my condition and it made the fix even harder).
Therefore, according to my investigation so far, I feel I, as a 3rd party developer, cannot fix it.

I heard from some users facing this issue that this was fixed on macOS 13 Ventura.
Does the same go for you?

**Comment by 1024jp** [comment] 2022-12-03 03:26
FYI, you can strangely detour the issue by changing the CotEditor's localization from Japanese to another language (e.g. in English).
Because this issue can happen only in the Japanese environment.

**Comment by faiare** [comment] 2022-12-03 06:57
Thank you for your reply.
That's right at all.
After updating to mac OS 13, this issue was resolved.

**Comment by 1024jp** [comment] 2022-12-04 06:27
Thank you for the reply. Well then, let me close this issue (although the issue still exists on macOS 12...).

**Closed by 1024jp** 2022-12-04 06:27 UTC
Labels: bug,  matter
