### ISSUE TITLE
CotEditor Updates Revert Keybindings to Default

### ISSUE THREAD

**Issue by gregarios** [coteditor/CotEditor#1428] opened 2023-02-03 14:59 UTC
### Description

CotEditor updates unexpectedly erase custom key bindings.

### To Reproduce

1. Set up key bindings for various text transformations in CotEditor.
2. Update to the newest (or next) version of CotEditor.
3. Keybindings are reset to default.

### Expected behavior

Keep keybinding settings so automatic CotEditor updates via the Apple App Store do not revert them to default.

### CotEditor version

4.4.4 (548)

### macOS version

13.2 (Build 22D49)

### Additional context

This has happened each of the last 5 or 6 updates.

**Comment by 1024jp** [comment] 2023-02-04 01:24
That sounds strange, because the current CotEditor do nothing like data migration or sanitization to user setting when it updated.

I'd like to know the following points:
1. Does it happen only after CotEditor was updated (e.g. from CotEditor 4.4.3 to 4.4.4), and not when just relaunched the app with the same version?
2. Are other settings, such as custom Theme, kept when updated?
3. Does performing First Aid with Disk Utility not solve the issue?
4. Could you share the key bindings file stored in `~/Library/Containers/com.coteditor.CotEditor/Data/Library/Application\ Support/CotEditor/KeyBindings`

**Comment by 1024jp** [comment] 2023-03-17 03:57
No reply?
Then, I close this as unreproducible issue.
If you still have problem, then just comment here.

**Closed by 1024jp** 2023-03-17 03:57 UTC
Labels: awaiting reply, potential bug (works for me)

**Comment by gregarios** [comment] 2023-03-17 04:50
Sorry about that I've been too busy to follow up on this further. I'll wait until I notice it again, if it happens. It could have been a Mojave issue too.

**Comment by 1024jp** [comment] 2023-03-17 07:04
Np.
Let me know if you find further information.
In addition, CotEditor updates implementation around key bindings in the next version.
I've not addressed especially for this issue, but therefore, the phenomenon can be changed on it.
