### ISSUE TITLE
Memory Leak when Find & Replace on Ventura and on M1

### ISSUE THREAD

**Issue by SHEN-Muchuan** [coteditor/CotEditor#1364] opened 2022-09-13 03:31 UTC
### Description

Memory Leak when Find & Replace on Ventura and on M1

### To Reproduce

I was trying to Find & Replace `\n` on a 1M big markdown file. And it causes a reproducible memory leak.

### CotEditor version

4.3.4

### macOS version

22A5342f

### Additional context

I don't know if it's a bug of CotEditor or a bug of the beta macOS, or the compatibility issue of M1 chip.

**Comment by 1024jp** [comment] 2022-09-14 00:51
Thank you for the reply. But I could not reproduce the issue in the same environment (macOS 13 beta 7, CotEditor 4.3.4, M1 Mac, and a Markdown file that has more than 1MB).

Could you describe more in detail what did you do, for example:
1. Open the Activity Monitor.app and switch the tab to "Memory".
2. Input `\n` in the find field and leave the replace field blank.
3. Press the "Replace" button in the find panel 10 times.
4. You can see the memory column in the activity panel increases to more than 1GB.

In addition, I'm also interested whether it happens also on CotEditor 4.4.0-beta, which is currently distributed in <https://coteditor.com/beta>.

**Comment by 1024jp** [comment] 2023-04-16 11:21
Closing due to no reply.

**Closed by 1024jp** 2023-04-16 11:21 UTC
Labels: awaiting reply, potential bug
