### ISSUE TITLE
Find/replace performance suffers again

### ISSUE THREAD

**Issue by lojza3d** [coteditor/CotEditor#931] opened 2019-02-20 20:07 UTC
In the current version 3.7.0 (342), the find/replace performance got significantly worse in comparison with the state after issue #876 had been fixed.

It's not that bad as before #876 had been reported, but the slow-down is considerable. My wild guess is that it's somehow related to the last (in the AppStore) reported fix "lines did not wrap correctly with vertical text orientation". According to my observation, lines wrapping has quite big impact on find/replace performance. If lines wrapping is "on" within a document, the find/replace is significantly slower (testing ona CSV file of approx. 500 lines and approx. 2000 characters per line).

Thanks for looking into this.

**Comment by 1024jp** [comment] 2019-02-21 04:09
Thank you for the feedback.

This would be not related to #876 but a side effect of fixing issue #917 (Sorry, but it's in Japanese. This issue is about replacing regex).
I've reverted one of the measurements for #876 in #917 in order to avoid that Replace All command ignored a single combining character, such as a diacritical mark. It seems to need to find another solution for performance optimization.
I'll try. So please wait a while.

**Comment by lojza3d** [comment] 2019-05-26 20:13
Hi, is there any progress on this? In the latest version 3.7.4 (351), the performance seems to slow down a bit again. See this: https://youtu.be/bOBPXNm7vwA

Also, I would like to suggest that new file should have line wrapping off by default. Pasting the large content when wrapping is on is also quite slow in comparison to pasting when wrapping is off.

Thanks for info & considering ;)

**Comment by 1024jp** [comment] 2020-02-28 01:16
In the last few versions that were released this year, including CotEditor 3.8.11 which is released today, CotEditor has done a bunch of performance optimizations. Consequently, now it becomes much easier to open and edit large documents than before.
Thus, I believe this issue is also solved now. I will close this issue within a few days, but if you have any feedback, I am welcome.

**Comment by lojza3d** [comment] 2020-02-28 13:22
Hi, I've tried the newest version 3.8.11 and the results are still somehow unconvicing. Tested with 1 416 lines copied from Excel file, each line having 45 columns (tabs), which I need to replace with semicolons. Now that's 63 720 replacements. Pasting from Excel, unwrapping the lines and perform find/replace - all these three actions took somehow longer time than I would expect.

See this screen recording: https://youtu.be/dDG8ppreSVE

However, it's been quite some time since I reported this issue, and, currently, I only scarcely need such a workflow. That being said, I'm quite OK with how CotEditor performs now, even if it is not "lightning fast".

**Comment by 1024jp** [comment] 2020-02-29 03:18
Thank you for the testing.
Hmm, if it's possible, could you give me a test file that can reproduce the issue?
You can send me it to coteditor.github@gmail.com

**Comment by 1024jp** [comment] 2020-03-02 23:21
@lojza3d I received the data file from you and observed the phenomenon. I'll work on it. Thank you!

**Comment by 1024jp** [comment] 2020-05-17 06:04
Thank you for the test file and sorry for taking a long time to reply.

I've invested more effort in this issue in the next CotEditor 3.9.0, and at last, 3.9.0 is now [beta testing](https://coteditor.com/beta).
I believe in this version, replacing a quite large number of matches needs significantly less time than previous versions.
I'll release the stable version within this month.
However, if you are interested in, please test it.

**Comment by 1024jp** [comment] 2020-05-28 04:10
I close this issue because of the release of CotEditor 3.9.0.
If you still have a performance issue related to find/replace, please post a comment here, or just create a new issue.

**Closed by 1024jp** 2020-05-28 04:10 UTC
Labels: request

**Comment by lojza3d** [comment] 2020-05-28 07:56
Thank you for looking into this. Copying huge text (1500+ lines, wrapped by default) still feels kind of cumbersome (~ 12 seconds before the text is displayed after pasting), but the find/replace is blazingly fast! 65 000+ replacements done in less than a second. Great job!
